### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-jsxhtml-freemarker#2]
@apuravchauhan Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by Scrum** [comment]
@apuravchauhan ping

**Comment by apuravchauhan** [comment]
@Scrum Thanks for considering this. Added you are collaborator. Let me know if I can help with anything else. And thanks for this awesome library

**Comment by Scrum** [comment]
@apuravchauhan Thanks but unfortunately this is not enough to move - I do not have access to the `settings` - for this I must be `owner`

**Comment by apuravchauhan** [comment]
@Scrum Repo transferred under your name

**Comment by Scrum** [comment]
@apuravchauhan Check access rights to this repository. Welcome aboard.
